#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Dev defaults (override in shell for production)
APP_ENV=${APP_ENV:-"dev"}
INTERNAL_TOKEN=${INTERNAL_TOKEN:-"dev-internal-token-change-me"}
AUTH_TOKEN_SECRET=${AUTH_TOKEN_SECRET:-"dev-auth-token-secret-32-bytes-minimum"}
AUTH_TOKEN_TTL=${AUTH_TOKEN_TTL:-"24h"}
ADMIN_TOKEN=${ADMIN_TOKEN:-"dev-admin-token-change-me"}

export APP_ENV INTERNAL_TOKEN AUTH_TOKEN_SECRET AUTH_TOKEN_TTL ADMIN_TOKEN

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost "$port" 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# NOTE: This script assumes PostgreSQL and Redis are already running.

# Matching
(cd exchange-matching && go run ./cmd/matching) &
wait_for_service 8082 "Matching"

# Clearing
(cd exchange-clearing && go run ./cmd/clearing) &
wait_for_service 8083 "Clearing"

# Order
(cd exchange-order && go run ./cmd/order) &
wait_for_service 8081 "Order"

# Marketdata
(cd exchange-marketdata && go run ./cmd/marketdata) &
wait_for_service 8084 "Marketdata"

# User
(cd exchange-user && go run ./cmd/user) &
wait_for_service 8085 "User"

# Wallet
(cd exchange-wallet && go run ./cmd/wallet) &
wait_for_service 8086 "Wallet"

# Admin
(cd exchange-admin && go run ./cmd/admin) &
wait_for_service 8087 "Admin"

# Gateway (depends on core services)
(cd exchange-gateway && go run ./cmd/gateway) &
wait_for_service 8080 "Gateway"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Gateway:    http://localhost:8080"
echo "  Order:      http://localhost:8081"
echo "  Matching:   http://localhost:8082"
echo "  Clearing:   http://localhost:8083"
echo "  Marketdata: http://localhost:8084"
echo "  User:       http://localhost:8085"
echo "  Wallet:     http://localhost:8086"
echo "  Admin:      http://localhost:8087"
echo ""
