#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost "$port" 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START INFRASTRUCTURE
# ============================================

if [ -f "exchange-common/docker-compose.yml" ]; then
    echo -e "${YELLOW}Starting infrastructure (postgres, redis)...${NC}"
    (cd exchange-common && docker-compose up -d postgres redis)
fi

# ============================================
# START SERVICES
# ============================================

# exchange-order
(cd exchange-order && go run ./cmd/order &) 
wait_for_service 8081 "exchange-order"

# exchange-admin
(cd exchange-admin && go run ./cmd/admin &) 
wait_for_service 8087 "exchange-admin"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  exchange-order: http://localhost:8081"
echo "  exchange-admin: http://localhost:8087"
echo ""
