name: Feature Request
description: Propose an enhancement for OpenExchange
title: "[Feature]: "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! Clear use cases help us prioritize.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: One sentence describing the feature
      placeholder: Add iceberg order support to matching engine
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve?
      placeholder: Traders need ... because ...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe your preferred design or behavior
      placeholder: Add new order type ... and API fields ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you evaluated

  - type: dropdown
    id: module
    attributes:
      label: Related Module
      options:
        - exchange-gateway
        - exchange-user
        - exchange-order
        - exchange-matching
        - exchange-clearing
        - exchange-marketdata
        - exchange-admin
        - exchange-wallet
        - exchange-common
        - docs
        - cross-module
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I checked existing issues and discussions first
          required: true
