#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost "$port" 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

ROOT_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"

# ============================================
# START SERVICES
# ============================================

# Clearing
cd "$ROOT_DIR/exchange-clearing" && go run ./cmd/clearing &
wait_for_service 8083 "Clearing"

# Wallet
cd "$ROOT_DIR/exchange-wallet" && go run ./cmd/wallet &
wait_for_service 8086 "Wallet"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Clearing: http://localhost:8083"
echo "  Wallet:   http://localhost:8086"
echo ""
