#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Matching Engine
cd /Users/jiesen/Desktop/交易所开发/exchange-matching && go run ./cmd/matching &
wait_for_service 8082 "Exchange Matching"

# Order Service
cd /Users/jiesen/Desktop/交易所开发/exchange-order && go run ./cmd/order &
wait_for_service 8081 "Exchange Order"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Exchange Matching: http://localhost:8082"
echo "  Exchange Order:    http://localhost:8081"
echo ""
